title	Fedora
sort-key fedora
linux	linux.efi
initrd	initramfs
#Fedora42
options console=tty0 console=ttyMSM0,115200n8 loglevel=3 splash root=UUID=3d5a63f7-e85b-4637-af14-a6963f0f48d8 rw

#armbian
#options console=tty0 console=ttyMSM0,115200n8 loglevel=3 splash root=UUID=8fd9b9e6-31df-4db5-8f23-e92117a329b5 rw

#ubuntu22.04
#options console=tty0 console=ttyMSM0,115200n8 loglevel=3 splash root=UUID=93afcbbe-875f-49b0-83da-ee8193f20ca5 rw
